package com.example.myproject.model.enums;

/**
 * מודול מקור של אירוע לוג.
 * מכסה את שכבת System, Services, Controllers ואינטגרציות.
 */
public enum SystemModule {

    // ===== System Core Layer =====
    SYSTEM_CORE,
    SYSTEM_RULES,
    USER_STATE_EVALUATOR,
    SYSTEM_SECURITY_CENTER,
    SYSTEM_AUDIT_TRAIL,
    SYSTEM_STATUS,
    SYSTEM_HEALTH_REGISTRY,
    SYSTEM_MONITORING_LAYER,
    SYSTEM_STORAGE_MANAGER,
    SYSTEM_LOAD_BALANCER,
    SYSTEM_EMERGENCY_RECOVERY,
    SYSTEM_NOTIFICATION_CENTER,
    SYSTEM_MESSAGE_BUS,
    SYSTEM_REGISTRAR,
    SYSTEM_SETTINGS_MANAGER,
    SYSTEM_CONFIG_PROVIDER,
    SYSTEM_INTEGRATION_LAYER,
    SYSTEM_DATA_PIPELINE,
    SYSTEM_CACHE_LAYER,
    SYSTEM_BACKGROUND_JOBS,
    SYSTEM_SCHEDULER,

    // ===== Domain Services =====
    USER_SERVICE,
    WEDDING_SERVICE,
    MATCH_SERVICE,
    CHAT_MESSAGE_SERVICE,
    NOTIFICATION_SERVICE,
    USER_ACTION_SERVICE,
    USER_PHOTO_SERVICE,
    BACKGROUND_SERVICE,
    OTP_SERVICE,
    INITIAL_MESSAGE_SERVICE,
    SYSTEM_LOG_SERVICE,

    // ===== Controllers / API =====
    USER_CONTROLLER,
    USER_ADMIN_CONTROLLER,
    USER_PHOTO_USER_CONTROLLER,
    USER_PHOTO_ADMIN_CONTROLLER,
    USER_ACTION_USER_CONTROLLER,
    USER_ACTION_OWNER_CONTROLLER,
    USER_ACTION_ADMIN_CONTROLLER,
    USER_ACTION_SYSTEM_CONTROLLER,
    WEDDING_PUBLIC_CONTROLLER,
    WEDDING_OWNER_CONTROLLER,
    WEDDING_ADMIN_CONTROLLER,
    MATCH_CONTROLLER,
    CHAT_MESSAGE_CONTROLLER,
    NOTIFICATION_USER_CONTROLLER,
    SYSTEM_CONTROLLER,

    // ===== Integrations =====
    EXTERNAL_SMS_GATEWAY,
    EXTERNAL_EMAIL_PROVIDER,
    EXTERNAL_PUSH_PROVIDER,
    EXTERNAL_STORAGE_PROVIDER,
    EXTERNAL_ANALYTICS,

    // ===== Data / Infra =====
    DATABASE,
    CACHE,
    FILE_STORAGE,
    MESSAGE_QUEUE,

    // ===== Frontend / Client =====
    WEB_CLIENT,
    MOBILE_CLIENT,
    BACKOFFICE_DASHBOARD,

    // ===== Fallback =====
    UNKNOWN
}