package com.example.myproject.model;

import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity                                 // ישות DB
@Table(name = "user_actions")          // טבלת user_actions
public class UserAction {

    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;                   // מפתח פעולה

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "actor_user_id", nullable = false)
    private User actor;                // מי ביצע

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "target_user_id")
    private User target;               // על מי הפעולה

    @Enumerated(EnumType.STRING)
    @Column(name = "action_type", nullable = false, length = 60)
    private UserActionType actionType; // סוג הפעולה (LIKE / VIEW / FREEZE…)

    @Enumerated(EnumType.STRING)
    @Column(name = "action_category", nullable = false, length = 40)
    private UserActionCategory category; // קטגוריה כללית (SOCIAL/CHAT/PROFILE)

    @Column(name = "wedding_id")
    private Long weddingId;            // בחתונה זו הפעולה התבצעה

    @Column(name = "origin_wedding_id")
    private Long originWeddingId;      // איפה הכירו לראשונה

    @Column(name = "match_id")
    private Long matchId;              // משויך למאץ'

    @Column(name = "action_group_id")
    private Long actionGroupId;        // קבוצת פעולות (זרימה אחת)

    @Column(name = "action_source", length = 40)
    private String source;             // מקור הפעולה (user/admin/system/ai)

    @Column(name = "auto_generated", nullable = false)
    private boolean autoGenerated = false; // נוצר אוטומטית?

    @Column(name = "metadata", length = 2000)
    private String metadata;           // מידע נוסף (JSON)

    @Column(name = "ip_address", length = 100)
    private String ipAddress;          // IP לבקרה

    @Column(name = "device_info", length = 300)
    private String deviceInfo;         // מכשיר

    @Column(nullable = false)
    private boolean active = true;     // פעולה פעילה?

    @Column(name = "list_name", length = 50)
    private String listName;           // ⭐ שם הרשימה (LIKE/FREEZE/MAYBE…)

    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt = LocalDateTime.now(); // זמן פעולה

    @Column(name = "updated_at")
    private LocalDateTime updatedAt;   // זמן עדכון

    // ===== Hooks =====

    @PrePersist
    protected void onCreate() {
        if (createdAt == null) createdAt = LocalDateTime.now();
        this.updatedAt = LocalDateTime.now();
    }

    @PreUpdate
    protected void onUpdate() {
        this.updatedAt = LocalDateTime.now();
    }

    // ===== Constructors =====

    public UserAction() {}

    public UserAction(User actor, User target,
                      UserActionType actionType,
                      UserActionCategory category,
                      Long weddingId, Long originWeddingId,
                      Long matchId, Long actionGroupId,
                      String source, boolean autoGenerated,
                      String metadata, String listName) {

        this.actor = actor;                 // מי ביצע
        this.target = target;               // על מי
        this.actionType = actionType;       // סוג פעולה
        this.category = category;           // קטגוריה
        this.weddingId = weddingId;         // בחתונה זו
        this.originWeddingId = originWeddingId;
        this.matchId = matchId;             // מאץ'
        this.actionGroupId = actionGroupId;
        this.source = source;               // מקור
        this.autoGenerated = autoGenerated; // אוטומטית?
        this.metadata = metadata;
        this.listName = listName;           // ⭐ רשימה
        this.active = true;
        this.createdAt = LocalDateTime.now();
        this.updatedAt = this.createdAt;
    }

    // ===== Getters/Setters =====

    public Long getId() { return id; }

    public User getActor() { return actor; }
    public void setActor(User actor) { this.actor = actor; }

    public User getTarget() { return target; }
    public void setTarget(User target) { this.target = target; }

    public UserActionType getActionType() { return actionType; }
    public void setActionType(UserActionType actionType) { this.actionType = actionType; }

    public UserActionCategory getCategory() { return category; }
    public void setCategory(UserActionCategory category) { this.category = category; }

    public Long getWeddingId() { return weddingId; }
    public void setWeddingId(Long weddingId) { this.weddingId = weddingId; }

    public Long getOriginWeddingId() { return originWeddingId; }
    public void setOriginWeddingId(Long originWeddingId) { this.originWeddingId = originWeddingId; }

    public Long getMatchId() { return matchId; }
    public void setMatchId(Long matchId) { this.matchId = matchId; }

    public Long getActionGroupId() { return actionGroupId; }
    public void setActionGroupId(Long actionGroupId) { this.actionGroupId = actionGroupId; }

    public String getSource() { return source; }
    public void setSource(String source) { this.source = source; }

    public boolean isAutoGenerated() { return autoGenerated; }
    public void setAutoGenerated(boolean autoGenerated) { this.autoGenerated = autoGenerated; }

    public String getMetadata() { return metadata; }
    public void setMetadata(String metadata) { this.metadata = metadata; }

    public String getIpAddress() { return ipAddress; }
    public void setIpAddress(String ipAddress) { this.ipAddress = ipAddress; }

    public String getDeviceInfo() { return deviceInfo; }
    public void setDeviceInfo(String deviceInfo) { this.deviceInfo = deviceInfo; }

    public boolean isActive() { return active; }
    public void setActive(boolean active) { this.active = active; }

    public String getListName() { return listName; }
    public void setListName(String listName) { this.listName = listName; }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }

    public LocalDateTime getUpdatedAt() { return updatedAt; }
    public void setUpdatedAt(LocalDateTime updatedAt) { this.updatedAt = updatedAt; }
}