package com.example.myproject.model;

import com.example.myproject.model.enums.UserActionType;
import com.example.myproject.model.enums.UserActionCategory;
import jakarta.persistence.*;
import java.time.LocalDateTime;

@Entity
@Table(
        name = "user_actions",
        indexes = {
                @Index(name = "idx_action_actor", columnList = "actor_user_id"),
                @Index(name = "idx_action_target", columnList = "target_user_id"),
                @Index(name = "idx_action_type", columnList = "action_type"),
                @Index(name = "idx_action_category", columnList = "action_category"),
                @Index(name = "idx_action_wedding", columnList = "wedding_id"),
                @Index(name = "idx_action_group", columnList = "action_group_id"),
                @Index(name = "idx_action_created", columnList = "created_at")
        }
)
public class UserAction {

    // ======================================================
    // 🔵 מזהה
    // ======================================================
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    // ======================================================
    // 🔵 Actor / Target
    // ======================================================
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "actor_user_id", nullable = false)
    private User actor;

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "target_user_id")
    private User target;

    // ======================================================
    // 🔵 Action Type / Category
    // ======================================================
    @Enumerated(EnumType.STRING)
    @Column(name = "action_type", nullable = false, length = 60)
    private UserActionType actionType;

    @Enumerated(EnumType.STRING)
    @Column(name = "action_category", nullable = false, length = 40)
    private UserActionCategory category;

    // ======================================================
    // 🔵 קשרים לוגיים
    // ======================================================
    @Column(name = "wedding_id")
    private Long weddingId;

    @Column(name = "origin_wedding_id")
    private Long originWeddingId;

    @Column(name = "match_id")
    private Long matchId;

    // קבוצת פעולות (פעולות מאותו flow)
    @Column(name = "action_group_id")
    private Long actionGroupId;

    // ======================================================
    // 🔵 מקור הפעולה
    // ======================================================
    @Column(name = "action_source", length = 40)
    private String source;   // user / admin / system / ai

    @Column(name = "auto_generated", nullable = false)
    private boolean autoGenerated = false;

    // ======================================================
    // 🔵 רשימות (Like / Freeze / Maybe / Dislike)
    // ======================================================
    @Column(name = "list_name", length = 50)
    private String listName;

    // ======================================================
    // 🔵 Metadata
    // ======================================================
    @Column(name = "metadata", length = 3000)
    private String metadata;

    // ======================================================
    // 🔵 ניטור / אבטחה
    // ======================================================
    @Column(name = "ip_address", length = 100)
    private String ipAddress;

    @Column(name = "device_info", length = 300)
    private String deviceInfo;

    // ======================================================
    // 🔵 סטטוס
    // ======================================================
    @Column(nullable = false)
    private boolean active = true;

    // ======================================================
    // 🔵 זמנים
    // ======================================================
    @Column(name = "created_at", nullable = false)
    private LocalDateTime createdAt = LocalDateTime.now();

    @Column(name = "updated_at")
    private LocalDateTime updatedAt;

    @Column(name = "reason", length = 500)
    private String reason;

    // ======================================================
    // 🔵 Hooks
    // ======================================================
    @PrePersist
    protected void onCreate() {
        if (createdAt == null)
            createdAt = LocalDateTime.now();
        updatedAt = createdAt;
    }

    @PreUpdate
    protected void onUpdate() {
        updatedAt = LocalDateTime.now();
    }

    // ======================================================
    // 🔵 Constructors
    // ======================================================
    public UserAction() {}

    public UserAction(
            User actor,
            User target,
            UserActionType actionType,
            UserActionCategory category,
            Long weddingId,
            Long originWeddingId,
            Long matchId,
            Long actionGroupId,
            String source,
            boolean autoGenerated,
            String metadata,
            String listName
    ) {
        this.actor = actor;
        this.target = target;
        this.actionType = actionType;
        this.category = category;
        this.weddingId = weddingId;
        this.originWeddingId = originWeddingId;
        this.matchId = matchId;
        this.actionGroupId = actionGroupId;
        this.source = source;
        this.autoGenerated = autoGenerated;
        this.metadata = metadata;
        this.listName = listName;
        this.createdAt = LocalDateTime.now();
        this.updatedAt = this.createdAt;
    }

    // ======================================================
    // 🔵 Getters & Setters
    // ======================================================

    public Long getId() { return id; }

    public User getActor() { return actor; }
    public void setActor(User actor) { this.actor = actor; }

    public User getTarget() { return target; }
    public void setTarget(User target) { this.target = target; }

    public UserActionType getActionType() { return actionType; }
    public void setActionType(UserActionType actionType) { this.actionType = actionType; }

    public UserActionCategory getCategory() { return category; }
    public void setCategory(UserActionCategory category) { this.category = category; }

    public Long getWeddingId() { return weddingId; }
    public void setWeddingId(Long weddingId) { this.weddingId = weddingId; }

    public Long getOriginWeddingId() { return originWeddingId; }
    public void setOriginWeddingId(Long originWeddingId) { this.originWeddingId = originWeddingId; }

    public Long getMatchId() { return matchId; }
    public void setMatchId(Long matchId) { this.matchId = matchId; }

    public Long getActionGroupId() { return actionGroupId; }
    public void setActionGroupId(Long actionGroupId) { this.actionGroupId = actionGroupId; }

    public String getSource() { return source; }
    public void setSource(String source) { this.source = source; }

    public boolean isAutoGenerated() { return autoGenerated; }
    public void setAutoGenerated(boolean autoGenerated) { this.autoGenerated = autoGenerated; }

    public String getMetadata() { return metadata; }
    public void setMetadata(String metadata) { this.metadata = metadata; }

    public String getListName() { return listName; }
    public void setListName(String listName) { this.listName = listName; }

    public String getIpAddress() { return ipAddress; }
    public void setIpAddress(String ipAddress) { this.ipAddress = ipAddress; }

    public String getDeviceInfo() { return deviceInfo; }
    public void setDeviceInfo(String deviceInfo) { this.deviceInfo = deviceInfo; }

    public boolean isActive() { return active; }
    public void setActive(boolean active) { this.active = active; }

    public LocalDateTime getCreatedAt() { return createdAt; }
    public void setCreatedAt(LocalDateTime createdAt) { this.createdAt = createdAt; }

    public LocalDateTime getUpdatedAt() { return updatedAt; }
    public void setUpdatedAt(LocalDateTime updatedAt) { this.updatedAt = updatedAt; }

    public String getReason() { return reason; }
    public void setReason(String reason) { this.reason = reason; }
}