package com.example.myproject.repository;

import com.example.myproject.model.UserAction;
import com.example.myproject.model.UserActionType;
import com.example.myproject.model.UserActionCategory;
import com.example.myproject.model.User;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.time.LocalDateTime;
import java.util.List;

@Repository
public interface UserActionRepository extends JpaRepository<UserAction, Long> {

    // 🔵 פעולות לפי מי שביצע
    List<UserAction> findByActor(User actor);                        // כל הפעולות שלי
    List<UserAction> findByActorAndActiveTrue(User actor);           // פעולות פעילות שלי
    List<UserAction> findByActorAndActionTypeAndActiveTrue(User actor, UserActionType type); // פעולות מסוג מסוים שלי

    // 🔵 לפי מזהה Actor
    List<UserAction> findByActorId(Long actorId);
    List<UserAction> findByActorIdAndActiveTrue(Long actorId);

    // 🔵 פעולות שנעשו עליי
    List<UserAction> findByTarget(User target);
    List<UserAction> findByTargetAndActiveTrue(User target);
    List<UserAction> findByTargetAndActionType(User target, UserActionType type);

    // 🔵 לפי מזהה Target
    List<UserAction> findByTargetId(Long targetId);
    List<UserAction> findByTargetIdAndActiveTrue(Long targetId);

    // 🔵 פעולה אחרונה בין שני משתמשים
    UserAction findTopByActorAndTargetAndActionTypeAndActiveTrueOrderByCreatedAtDesc(
            User actor, User target, UserActionType type
    );

    UserAction findTopByActorAndTargetOrderByCreatedAtDesc(
            User actor, User target
    );

    // 🔵 כל היסטוריית הפעולות ביניהם
    List<UserAction> findByActorAndTarget(User actor, User target);

    // 🔵 לפי סוג פעולה
    List<UserAction> findByActionType(UserActionType type);

    // 🔵 לפי קטגוריה
    List<UserAction> findByCategory(UserActionCategory category);

    // 🔵 לפי חתונה
    List<UserAction> findByWeddingId(Long weddingId);
    List<UserAction> findByOriginWeddingId(Long weddingId);

    // 🔵 לפי מאץ'
    List<UserAction> findByMatchId(Long matchId);

    // 🔵 לפי groupId
    List<UserAction> findByActionGroupId(Long actionGroupId);

    // 🔵 לפי מקור פעולה
    List<UserAction> findBySource(String source);

    // 🔵 פעולות אוטומטיות
    List<UserAction> findByAutoGeneratedTrue();
    List<UserAction> findByAutoGeneratedFalse();

    // 🔵 פעולות פעילות / לא פעילות
    List<UserAction> findByActiveTrue();
    List<UserAction> findByActiveFalse();

    // 🔵 לפי טווחי זמן (סטטיסטיקות / Cron)
    List<UserAction> findByCreatedAtAfter(LocalDateTime time);
    List<UserAction> findByCreatedAtBefore(LocalDateTime time);
    List<UserAction> findByCreatedAtBetween(LocalDateTime start, LocalDateTime end);

    // ⭐ חדש — רשימות (Like/Freeze/Maybe/Waiting)
    List<UserAction> findByActorIdAndListName(Long actorId, String listName);  // כל הפעולות ברשימה מסוימת
}