package com.example.myproject.controller.useraction.system;

import com.example.myproject.model.UserAction;
import com.example.myproject.model.UserActionCategory;
import com.example.myproject.model.UserActionType;
import com.example.myproject.repository.UserActionRepository;
import com.example.myproject.service.UserActionService;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;

import java.time.LocalDateTime;
import java.time.format.DateTimeParseException;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;
import java.util.stream.Collectors;

/**
 * 🔵 UserActionSystemController
 *
 * קונטרולר פנימי למערכת / AI / CRON:
 * - יצירת פעולות אוטומטיות (autoGenerated=true)
 * - תמיכה ב-Group Actions (actionGroupId)
 * - שליפה לפי מקור (source=system/ai/admin)
 * - שליפה לפי AutoGenerated
 * - סטטיסטיקות צפיות בפרופיל (Profile Views Summary)
 * - חיפושי זמן (CreatedAt Between) לצרכי Cron / BI
 *
 * ⚠ קונטרולר זה *לא* מיועד לשימוש ישיר מה-Frontend של המשתמש,
 * אלא למודולי מערכת, Scheduler-ים, AI Matching Engine וכו'.
 */
@RestController
@RequestMapping("/api/system/user-actions")
public class UserActionSystemController {

    private final UserActionService userActionService;
    private final UserActionRepository userActionRepository;

    public UserActionSystemController(UserActionService userActionService,
                                      UserActionRepository userActionRepository) {
        this.userActionService = userActionService;
        this.userActionRepository = userActionRepository;
    }

    // ============================================================
    // 1️⃣ יצירת פעולה אוטומטית אחת (System / AI)
    // ============================================================

    /**
     * יצירת UserAction אחת עבור מודול מערכת / AI.
     *
     * POST /api/system/user-actions/record
     *
     * Request JSON:
     * {
     *   "actorUserId": 10,
     *   "targetUserId": 25,                // אופציונלי
     *   "weddingId": 5,                    // אופציונלי
     *   "originWeddingId": 3,              // אופציונלי
     *   "matchId": 100,                    // אופציונלי
     *   "actionType": "LIKE",              // חובה
     *   "category": "SOCIAL",              // אופציונלי, ברירת מחדל: SOCIAL
     *   "metadata": "{ \"reason\": \"AI\" }",
     *   "source": "ai",                    // ברירת מחדל: "system"
     *   "autoGenerated": true,             // ברירת מחדל: true
     *   "listName": "LIKE",                // אופציונלי
     *   "actionGroupId": 999               // אופציונלי
     * }
     */
    @PostMapping("/record")
    public ResponseEntity<UserAction> recordSystemAction(@RequestBody RecordSystemActionRequest request) {
        if (request.getActorUserId() == null) {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
        }
        if (request.getActionType() == null) {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
        }

        // ברירת מחדל לקטגוריה – SOCIAL אם לא נשלח
        UserActionCategory category = request.getCategory() != null
                ? request.getCategory()
                : UserActionCategory.SOCIAL;

        // מקור ברירת מחדל
        String source = (request.getSource() == null || request.getSource().isBlank())
                ? "system"
                : request.getSource();

        // autoGenerated ברירת מחדל = true
        boolean autoGenerated = (request.getAutoGenerated() == null)
                ? true
                : request.getAutoGenerated();

        try {
            UserAction action = userActionService.recordUserAction(
                    request.getActorUserId(),
                    request.getTargetUserId(),
                    request.getWeddingId(),
                    request.getOriginWeddingId(),
                    request.getMatchId(),
                    request.getActionType(),
                    category,
                    request.getMetadata(),
                    source,
                    autoGenerated,
                    request.getListName(),
                    request.getActionGroupId()
            );

            return ResponseEntity.status(HttpStatus.CREATED).body(action);
        } catch (IllegalArgumentException ex) {
            // Actor/Target לא קיימים או פרמטר אחר שגוי
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
        }
    }

    // ============================================================
    // 2️⃣ Batch / Group Actions – מספר פעולות במכה אחת
    // ============================================================

    /**
     * יצירת מספר UserAction במכה אחת, עם אפשרות לשתף actionGroupId.
     *
     * POST /api/system/user-actions/record-batch
     *
     * Request JSON:
     * {
     *   "actionGroupId": 555,          // אופציונלי – אם לא נשלח, כל אחד ישתמש במה שיש לו
     *   "actions": [
     *     {
     *       "actorUserId": 10,
     *       "targetUserId": 20,
     *       "weddingId": 5,
     *       "actionType": "LIKE",
     *       "category": "SOCIAL",
     *       "source": "ai",
     *       "autoGenerated": true,
     *       "listName": "LIKE"
     *     },
     *     {
     *       "actorUserId": 11,
     *       "targetUserId": 21,
     *       "weddingId": 5,
     *       "actionType": "LIKE",
     *       "source": "ai",
     *       "autoGenerated": true,
     *       "listName": "LIKE"
     *     }
     *   ]
     * }
     */
    @PostMapping("/record-batch")
    public ResponseEntity<List<UserAction>> recordSystemActionsBatch(
            @RequestBody RecordSystemActionBatchRequest request) {

        if (request.getActions() == null || request.getActions().isEmpty()) {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
        }

        Long groupIdOverride = request.getActionGroupId();
        List<UserAction> result = new ArrayList<>();

        for (RecordSystemActionRequest actionReq : request.getActions()) {
            if (actionReq.getActorUserId() == null || actionReq.getActionType() == null) {
                continue; // מדלגים על רשומות שגויות
            }

            UserActionCategory category = actionReq.getCategory() != null
                    ? actionReq.getCategory()
                    : UserActionCategory.SOCIAL;

            String source = (actionReq.getSource() == null || actionReq.getSource().isBlank())
                    ? "system"
                    : actionReq.getSource();

            boolean autoGenerated = (actionReq.getAutoGenerated() == null)
                    ? true
                    : actionReq.getAutoGenerated();

            Long finalGroupId = (groupIdOverride != null)
                    ? groupIdOverride
                    : actionReq.getActionGroupId();

            try {
                UserAction action = userActionService.recordUserAction(
                        actionReq.getActorUserId(),
                        actionReq.getTargetUserId(),
                        actionReq.getWeddingId(),
                        actionReq.getOriginWeddingId(),
                        actionReq.getMatchId(),
                        actionReq.getActionType(),
                        category,
                        actionReq.getMetadata(),
                        source,
                        autoGenerated,
                        actionReq.getListName(),
                        finalGroupId
                );
                result.add(action);
            } catch (IllegalArgumentException ignored) {
                // מדלגים על רשומות כושלות ולא מפילים את הכל
            }
        }

        if (result.isEmpty()) {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
        }

        return ResponseEntity.status(HttpStatus.CREATED).body(result);
    }

    // ============================================================
    // 3️⃣ שליפות לפי AutoGenerated / Source / Group
    // ============================================================

    /**
     * כל הפעולות האוטומטיות (autoGenerated=true),
     * אפשר לסנן לפי source (system/ai/admin וכו').
     *
     * GET /api/system/user-actions/auto?source=ai
     */
    @GetMapping("/auto")
    public ResponseEntity<List<UserAction>> getAutoGeneratedActions(
            @RequestParam(name = "source", required = false) String source) {

        List<UserAction> list = userActionRepository.findByAutoGeneratedTrue();

        if (source != null && !source.isBlank()) {
            String wanted = source.toLowerCase(Locale.ROOT);
            list = list.stream()
                    .filter(a -> a.getSource() != null &&
                            a.getSource().toLowerCase(Locale.ROOT).equals(wanted))
                    .collect(Collectors.toList());
        }

        return ResponseEntity.ok(list);
    }

    /**
     * כל הפעולות לפי מקור (source).
     *
     * GET /api/system/user-actions/by-source?source=system
     */
    @GetMapping("/by-source")
    public ResponseEntity<List<UserAction>> getActionsBySource(
            @RequestParam(name = "source") String source) {

        if (source == null || source.isBlank()) {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
        }
        List<UserAction> list = userActionRepository.findBySource(source);
        return ResponseEntity.ok(list);
    }

    /**
     * כל הפעולות בקבוצת פעולה מסוימת (actionGroupId).
     *
     * GET /api/system/user-actions/group/{groupId}
     */
    @GetMapping("/group/{groupId}")
    public ResponseEntity<List<UserAction>> getActionsByGroup(@PathVariable Long groupId) {
        List<UserAction> list = userActionRepository.findByActionGroupId(groupId);
        return ResponseEntity.ok(list);
    }

    // ============================================================
    // 4️⃣ שליפות System-Level לפי Actor / Target עם פילטרים
    // ============================================================

    /**
     * כל הפעולות של Actor מסוים מנקודת מבט מערכת,
     * עם אפשרות לסנן לפי autoGenerated ו/או listName.
     *
     * GET /api/system/user-actions/by-actor/{actorId}?autoOnly=true&listName=LIKE
     */
    @GetMapping("/by-actor/{actorId}")
    public ResponseEntity<List<UserAction>> getActionsByActorForSystem(
            @PathVariable Long actorId,
            @RequestParam(name = "autoOnly", required = false, defaultValue = "false") boolean autoOnly,
            @RequestParam(name = "listName", required = false) String listName) {

        List<UserAction> list = userActionService.getActionsByActor(actorId);

        if (autoOnly) {
            list = list.stream()
                    .filter(UserAction::isAutoGenerated)
                    .collect(Collectors.toList());
        }

        if (listName != null && !listName.isBlank()) {
            String wanted = listName.toUpperCase(Locale.ROOT);
            list = list.stream()
                    .filter(a -> a.getListName() != null &&
                            a.getListName().toUpperCase(Locale.ROOT).equals(wanted))
                    .collect(Collectors.toList());
        }

        return ResponseEntity.ok(list);
    }

    /**
     * כל הפעולות על Target מסוים מנקודת מבט מערכת,
     * עם אפשרות לסנן לפי autoGenerated.
     *
     * GET /api/system/user-actions/by-target/{targetId}?autoOnly=true
     */
    @GetMapping("/by-target/{targetId}")
    public ResponseEntity<List<UserAction>> getActionsByTargetForSystem(
            @PathVariable Long targetId,
            @RequestParam(name = "autoOnly", required = false, defaultValue = "false") boolean autoOnly) {

        List<UserAction> list = userActionService.getActionsByTarget(targetId);

        if (autoOnly) {
            list = list.stream()
                    .filter(UserAction::isAutoGenerated)
                    .collect(Collectors.toList());
        }

        return ResponseEntity.ok(list);
    }

    /**
     * כל הפעולות לפי Wedding מסוים (System view).
     *
     * GET /api/system/user-actions/by-wedding/{weddingId}
     */
    @GetMapping("/by-wedding/{weddingId}")
    public ResponseEntity<List<UserAction>> getActionsByWeddingForSystem(@PathVariable Long weddingId) {
        List<UserAction> list = userActionService.getActionsByWedding(weddingId);
        return ResponseEntity.ok(list);
    }

    /**
     * כל הפעולות לפי Match מסוים (System view).
     *
     * GET /api/system/user-actions/by-match/{matchId}
     */
    @GetMapping("/by-match/{matchId}")
    public ResponseEntity<List<UserAction>> getActionsByMatchForSystem(@PathVariable Long matchId) {
        List<UserAction> list = userActionService.getActionsByMatch(matchId);
        return ResponseEntity.ok(list);
    }

    // ============================================================
    // 5️⃣ חיפושי זמן – לצורך Cron / BI / מנוע התאמות
    // ============================================================

    /**
     * שליפת פעולות בטווח זמן, עם אפשרות סינון לפי:
     * - autoOnly (true/false)
     * - source (system/ai/...)
     * - actionType
     * - category
     *
     * GET /api/system/user-actions/by-time-range
     *     ?from=2025-01-01T00:00:00
     *     &to=2025-01-08T00:00:00
     *     &autoOnly=true
     *     &source=ai
     *     &actionType=LIKE
     *     &category=SOCIAL
     */
    @GetMapping("/by-time-range")
    public ResponseEntity<List<UserAction>> getActionsByTimeRange(
            @RequestParam("from") String fromStr,
            @RequestParam("to") String toStr,
            @RequestParam(name = "autoOnly", required = false, defaultValue = "false") boolean autoOnly,
            @RequestParam(name = "source", required = false) String source,
            @RequestParam(name = "actionType", required = false) UserActionType actionType,
            @RequestParam(name = "category", required = false) UserActionCategory category) {

        LocalDateTime from;
        LocalDateTime to;

        try {
            from = LocalDateTime.parse(fromStr);
            to = LocalDateTime.parse(toStr);
        } catch (DateTimeParseException ex) {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
        }

        List<UserAction> list = userActionRepository.findByCreatedAtBetween(from, to);

        if (autoOnly) {
            list = list.stream()
                    .filter(UserAction::isAutoGenerated)
                    .collect(Collectors.toList());
        }

        if (source != null && !source.isBlank()) {
            String wanted = source.toLowerCase(Locale.ROOT);
            list = list.stream()
                    .filter(a -> a.getSource() != null &&
                            a.getSource().toLowerCase(Locale.ROOT).equals(wanted))
                    .collect(Collectors.toList());
        }

        if (actionType != null) {
            list = list.stream()
                    .filter(a -> a.getActionType() == actionType)
                    .collect(Collectors.toList());
        }

        if (category != null) {
            list = list.stream()
                    .filter(a -> a.getCategory() == category)
                    .collect(Collectors.toList());
        }

        return ResponseEntity.ok(list);
    }

    // ============================================================
    // 6️⃣ Profile Views – Count + Summary Notification (אפיון 2025)
    // ============================================================

    /**
     * ספירת צפיות בפרופיל של משתמש בטווח זמן.
     *
     * GET /api/system/user-actions/profile-views/count
     *     ?userId=123
     *     &from=2025-01-01T00:00:00
     *     &to=2025-01-08T00:00:00
     */
    @GetMapping("/profile-views/count")
    public ResponseEntity<ProfileViewsCountResponse> countProfileViews(
            @RequestParam("userId") Long userId,
            @RequestParam("from") String fromStr,
            @RequestParam("to") String toStr) {

        LocalDateTime from;
        LocalDateTime to;

        try {
            from = LocalDateTime.parse(fromStr);
            to = LocalDateTime.parse(toStr);
        } catch (DateTimeParseException ex) {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
        }

        int count = userActionService.countProfileViewsForUserInPeriod(userId, from, to);

        ProfileViewsCountResponse resp = new ProfileViewsCountResponse();
        resp.setUserId(userId);
        resp.setFrom(from);
        resp.setTo(to);
        resp.setViewsCount(count);

        return ResponseEntity.ok(resp);
    }

    /**
     * שליחת התראת Summary של צפיות בפרופיל למשתמש אחד.
     * משתמש ב-UserActionService.sendProfileViewsSummary(...)
     *
     * POST /api/system/user-actions/profile-views/summary
     *
     * Request JSON:
     * {
     *   "userId": 123,
     *   "periodLabel": "בשבוע האחרון",
     *   "from": "2025-01-01T00:00:00",
     *   "to": "2025-01-08T00:00:00"
     * }
     */
    @PostMapping("/profile-views/summary")
    public ResponseEntity<Void> sendProfileViewsSummary(
            @RequestBody ProfileViewsSummaryRequest request) {

        if (request.getUserId() == null ||
                request.getFrom() == null ||
                request.getTo() == null) {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
        }

        try {
            LocalDateTime from = LocalDateTime.parse(request.getFrom());
            LocalDateTime to = LocalDateTime.parse(request.getTo());

            userActionService.sendProfileViewsSummary(
                    request.getUserId(),
                    request.getPeriodLabel(),
                    from,
                    to
            );
            return ResponseEntity.ok().build();
        } catch (DateTimeParseException ex) {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
        }
    }

    /**
     * טריגר "דמוי Cron" – שליחת סיכום צפיות למספר משתמשים במכה אחת.
     * אפשר להשתמש ב-Scheduler חיצוני שיקרא לאנדפוינט הזה.
     *
     * POST /api/system/user-actions/profile-views/summary-batch
     *
     * Request JSON:
     * {
     *   "userIds": [1,2,3],
     *   "periodLabel": "בשבוע האחרון",
     *   "from": "2025-01-01T00:00:00",
     *   "to": "2025-01-08T00:00:00"
     * }
     */
    @PostMapping("/profile-views/summary-batch")
    public ResponseEntity<Void> sendProfileViewsSummaryBatch(
            @RequestBody ProfileViewsSummaryBatchRequest request) {

        if (request.getUserIds() == null || request.getUserIds().isEmpty()
                || request.getFrom() == null || request.getTo() == null) {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
        }

        try {
            LocalDateTime from = LocalDateTime.parse(request.getFrom());
            LocalDateTime to = LocalDateTime.parse(request.getTo());

            for (Long userId : request.getUserIds()) {
                userActionService.sendProfileViewsSummary(
                        userId,
                        request.getPeriodLabel(),
                        from,
                        to
                );
            }
            return ResponseEntity.ok().build();
        } catch (DateTimeParseException ex) {
            return ResponseEntity.status(HttpStatus.BAD_REQUEST).build();
        }
    }

    // ============================================================
    // DTOs פנימיים – Request / Response
    // ============================================================

    public static class RecordSystemActionRequest {
        private Long actorUserId;
        private Long targetUserId;
        private Long weddingId;
        private Long originWeddingId;
        private Long matchId;
        private UserActionType actionType;
        private UserActionCategory category;
        private String metadata;
        private String source;
        private Boolean autoGenerated;
        private String listName;
        private Long actionGroupId;

        public Long getActorUserId() { return actorUserId; }
        public void setActorUserId(Long actorUserId) { this.actorUserId = actorUserId; }

        public Long getTargetUserId() { return targetUserId; }
        public void setTargetUserId(Long targetUserId) { this.targetUserId = targetUserId; }

        public Long getWeddingId() { return weddingId; }
        public void setWeddingId(Long weddingId) { this.weddingId = weddingId; }

        public Long getOriginWeddingId() { return originWeddingId; }
        public void setOriginWeddingId(Long originWeddingId) { this.originWeddingId = originWeddingId; }

        public Long getMatchId() { return matchId; }
        public void setMatchId(Long matchId) { this.matchId = matchId; }

        public UserActionType getActionType() { return actionType; }
        public void setActionType(UserActionType actionType) { this.actionType = actionType; }

        public UserActionCategory getCategory() { return category; }
        public void setCategory(UserActionCategory category) { this.category = category; }

        public String getMetadata() { return metadata; }
        public void setMetadata(String metadata) { this.metadata = metadata; }

        public String getSource() { return source; }
        public void setSource(String source) { this.source = source; }

        public Boolean getAutoGenerated() { return autoGenerated; }
        public void setAutoGenerated(Boolean autoGenerated) { this.autoGenerated = autoGenerated; }

        public String getListName() { return listName; }
        public void setListName(String listName) { this.listName = listName; }

        public Long getActionGroupId() { return actionGroupId; }
        public void setActionGroupId(Long actionGroupId) { this.actionGroupId = actionGroupId; }
    }

    public static class RecordSystemActionBatchRequest {
        private Long actionGroupId;
        private List<RecordSystemActionRequest> actions;

        public Long getActionGroupId() { return actionGroupId; }
        public void setActionGroupId(Long actionGroupId) { this.actionGroupId = actionGroupId; }

        public List<RecordSystemActionRequest> getActions() { return actions; }
        public void setActions(List<RecordSystemActionRequest> actions) { this.actions = actions; }
    }

    public static class ProfileViewsCountResponse {
        private Long userId;
        private LocalDateTime from;
        private LocalDateTime to;
        private int viewsCount;

        public Long getUserId() { return userId; }
        public void setUserId(Long userId) { this.userId = userId; }

        public LocalDateTime getFrom() { return from; }
        public void setFrom(LocalDateTime from) { this.from = from; }

        public LocalDateTime getTo() { return to; }
        public void setTo(LocalDateTime to) { this.to = to; }

        public int getViewsCount() { return viewsCount; }
        public void setViewsCount(int viewsCount) { this.viewsCount = viewsCount; }
    }

    public static class ProfileViewsSummaryRequest {
        private Long userId;
        private String periodLabel;
        private String from;
        private String to;

        public Long getUserId() { return userId; }
        public void setUserId(Long userId) { this.userId = userId; }

        public String getPeriodLabel() { return periodLabel; }
        public void setPeriodLabel(String periodLabel) { this.periodLabel = periodLabel; }

        public String getFrom() { return from; }
        public void setFrom(String from) { this.from = from; }

        public String getTo() { return to; }
        public void setTo(String to) { this.to = to; }
    }

    public static class ProfileViewsSummaryBatchRequest {
        private List<Long> userIds;
        private String periodLabel;
        private String from;
        private String to;

        public List<Long> getUserIds() { return userIds; }
        public void setUserIds(List<Long> userIds) { this.userIds = userIds; }

        public String getPeriodLabel() { return periodLabel; }
        public void setPeriodLabel(String periodLabel) { this.periodLabel = periodLabel; }

        public String getFrom() { return from; }
        public void setFrom(String from) { this.from = from; }

        public String getTo() { return to; }
        public void setTo(String to) { this.to = to; }
    }
}