package com.example.myproject.service;

import com.example.myproject.model.User;
import com.example.myproject.model.UserAction;
import com.example.myproject.model.enums.SystemActionType;
import com.example.myproject.model.enums.SystemModule;
import com.example.myproject.model.enums.SystemSeverityLevel;
import com.example.myproject.model.enums.UserActionCategory;
import com.example.myproject.model.enums.UserActionType;
import com.example.myproject.repository.UserActionRepository;
import com.example.myproject.repository.UserRepository;
import com.example.myproject.service.System.SystemLogService;
import com.example.myproject.service.System.SystemSettingsService;
import com.example.myproject.service.User.UserStateEvaluatorService;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.Duration;
import java.time.LocalDateTime;
import java.util.*;
import java.util.concurrent.ThreadLocalRandom;
import java.util.concurrent.atomic.AtomicInteger;
import java.util.stream.Collectors;

@Service
@Transactional
public class UserActionService {

    private static final String K_AUDIT_ENABLED = "userAction.audit.enabled";

    private static final String K_RATE_MIN_SECONDS = "userAction.rate.minSeconds";                 // default 2
    private static final String K_RATE_MIN_SECONDS_HEAVY = "userAction.rate.minSeconds.heavy";     // default 5
    private static final String K_RATE_WINDOW_DUP_SECONDS = "userAction.rate.dupWindowSeconds";    // default 10

    private static final String K_PURGE_DAYS_ACTIVE = "userAction.purge.days.active";              // default 365
    private static final String K_PURGE_DAYS_INACTIVE = "userAction.purge.days.inactive";          // default 90

    private static final String K_HEAVY_ACTION_TYPES = "userAction.rate.heavyActionTypes";         // CSV

    private static final String K_MONITOR_ENABLED = "userAction.monitor.enabled";                  // default true
    private static final String K_MONITOR_WINDOW_SECONDS = "userAction.monitor.windowSeconds";     // default 180
    private static final String K_MONITOR_THRESHOLD = "userAction.monitor.threshold";              // default 30

    private static final String K_SYSTEM_ACTOR_USER_ID = "userAction.systemActorUserId";           // required
    private static final String K_MAX_PAGE_SIZE = "userAction.query.maxPageSize";                  // default 200

    private final UserActionRepository repo;
    private final UserRepository userRepo;
    private final SystemSettingsService settings;
    private final SystemLogService systemLogService;
    private final UserStateEvaluatorService userStateEvaluator;

    private final long nodeSalt = ThreadLocalRandom.current().nextLong(100_000L, 999_999L);
    private final AtomicInteger groupSeq = new AtomicInteger(0);

    public UserActionService(UserActionRepository repo,
                             UserRepository userRepo,
                             SystemSettingsService settings,
                             SystemLogService systemLogService,
                             UserStateEvaluatorService userStateEvaluator) {
        this.repo = repo;
        this.userRepo = userRepo;
        this.settings = settings;
        this.systemLogService = systemLogService;
        this.userStateEvaluator = userStateEvaluator;
    }

    public static class CreateActionCommand {
        public Long actorUserId;
        public Long targetUserId;

        public UserActionType actionType;
        public UserActionCategory category;

        public Long weddingId;
        public Long originWeddingId;
        public Long matchId;
        public Long actionGroupId;

        public String source;            // user/admin/system/ai
        public boolean autoGenerated;    // system/ai
        public boolean active = true;

        public String listName;
        public String metadata;
        public String reason;

        public String ipAddress;
        public String deviceInfo;

        public boolean enforceRateLimit = true;
        public boolean enforceCooldownSameType = true;
        public boolean preventDuplicates = true;
        public boolean requireCanLike = false;
        public boolean requireCanSendMessage = false;

        public SystemActionType auditActionType;
        public SystemModule auditModule;
        public SystemSeverityLevel auditSeverity = SystemSeverityLevel.INFO;
        public boolean auditAutomated = false;
        public String auditRequestId;
        public String auditContextJson;
    }

    public static class BatchResult {
        private final int requested;
        private final int created;
        private final int skippedAsDuplicate;
        private final int blockedByRateOrState;

        public BatchResult(int requested, int created, int skippedAsDuplicate, int blockedByRateOrState) {
            this.requested = requested;
            this.created = created;
            this.skippedAsDuplicate = skippedAsDuplicate;
            this.blockedByRateOrState = blockedByRateOrState;
        }

        public int getRequested() { return requested; }
        public int getCreated() { return created; }
        public int getSkippedAsDuplicate() { return skippedAsDuplicate; }
        public int getBlockedByRateOrState() { return blockedByRateOrState; }
    }

    public UserAction record(CreateActionCommand cmd) {
        Objects.requireNonNull(cmd, "cmd is null");
        validateCmd(cmd);

        User actor = getUserOrThrow(cmd.actorUserId);
        User target = (cmd.targetUserId == null) ? null : getUserOrThrow(cmd.targetUserId);

        enforceUserState(cmd, actor);

        if (cmd.enforceRateLimit) enforceRateLimitAnyAction(cmd.actorUserId, cmd.actionType);
        if (cmd.enforceCooldownSameType) enforceCooldownSameType(cmd.actorUserId, cmd.actionType);

        if (cmd.preventDuplicates) {
            UserAction dup = findRecentDuplicate(cmd);
            if (dup != null) {
                auditIfNeeded(cmd, actor.getId(), "SKIP_DUPLICATE userActionId=" + dup.getId());
                return dup;
            }
        }

        Long groupId = (cmd.actionGroupId != null) ? cmd.actionGroupId : nextGroupIdIfMissing(cmd);

        UserAction ua = new UserAction(
                actor,
                target,
                cmd.actionType,
                cmd.category,
                cmd.weddingId,
                cmd.originWeddingId,
                cmd.matchId,
                groupId,
                safeTrim(cmd.source),
                cmd.autoGenerated,
                cmd.metadata,
                cmd.listName
        );
        ua.setActive(cmd.active);
        ua.setReason(safeTrim(cmd.reason));
        ua.setIpAddress(safeTrim(cmd.ipAddress));
        ua.setDeviceInfo(safeTrim(cmd.deviceInfo));

        UserAction saved = repo.save(ua);

        monitorSuspiciousIfEnabled(actor.getId());
        auditIfNeeded(cmd, actor.getId(), "CREATED userActionId=" + saved.getId());

        return saved;
    }

    public BatchResult recordBatch(List<CreateActionCommand> commands) {
        if (commands == null || commands.isEmpty()) return new BatchResult(0, 0, 0, 0);

        Set<Long> ids = new HashSet<>();
        for (CreateActionCommand c : commands) {
            if (c == null) continue;
            if (c.actorUserId != null) ids.add(c.actorUserId);
            if (c.targetUserId != null) ids.add(c.targetUserId);
        }

        Map<Long, User> users = userRepo.findAllById(ids).stream()
                .filter(Objects::nonNull)
                .collect(Collectors.toMap(User::getId, u -> u, (a, b) -> a));

        int created = 0;
        int dup = 0;
        int blocked = 0;

        for (CreateActionCommand cmd : commands) {
            if (cmd == null) continue;
            try {
                validateCmd(cmd);

                if (cmd.preventDuplicates && findRecentDuplicate(cmd) != null) {
                    dup++;
                    continue;
                }

                User actor = users.get(cmd.actorUserId);
                User target = (cmd.targetUserId == null) ? null : users.get(cmd.targetUserId);

                if (actor == null) throw new IllegalArgumentException("User not found: " + cmd.actorUserId);
                if (cmd.targetUserId != null && target == null) throw new IllegalArgumentException("User not found: " + cmd.targetUserId);

                enforceUserState(cmd, actor);

                if (cmd.enforceRateLimit) enforceRateLimitAnyAction(cmd.actorUserId, cmd.actionType);
                if (cmd.enforceCooldownSameType) enforceCooldownSameType(cmd.actorUserId, cmd.actionType);

                Long groupId = (cmd.actionGroupId != null) ? cmd.actionGroupId : nextGroupIdIfMissing(cmd);

                UserAction ua = new UserAction(
                        actor,
                        target,
                        cmd.actionType,
                        cmd.category,
                        cmd.weddingId,
                        cmd.originWeddingId,
                        cmd.matchId,
                        groupId,
                        safeTrim(cmd.source),
                        cmd.autoGenerated,
                        cmd.metadata,
                        cmd.listName
                );
                ua.setActive(cmd.active);
                ua.setReason(safeTrim(cmd.reason));
                ua.setIpAddress(safeTrim(cmd.ipAddress));
                ua.setDeviceInfo(safeTrim(cmd.deviceInfo));

                repo.save(ua);
                created++;

            } catch (RuntimeException ex) {
                blocked++;
            }
        }

        Long firstActor = commands.stream()
                .filter(Objects::nonNull)
                .map(c -> c.actorUserId)
                .filter(Objects::nonNull)
                .findFirst()
                .orElse(null);

        if (firstActor != null) {
            try { monitorSuspiciousIfEnabled(firstActor); } catch (Exception ignore) {}
        }

        return new BatchResult(commands.size(), created, dup, blocked);
    }

    public UserAction recordUserAction(Long actorId,
                                       Long targetId,
                                       UserActionType type,
                                       UserActionCategory category,
                                       Long weddingId,
                                       Long matchId,
                                       String listName,
                                       String metadata,
                                       String ip,
                                       String deviceInfo) {

        CreateActionCommand cmd = new CreateActionCommand();
        cmd.actorUserId = actorId;
        cmd.targetUserId = targetId;
        cmd.actionType = type;
        cmd.category = category;
        cmd.weddingId = weddingId;
        cmd.matchId = matchId;
        cmd.listName = listName;
        cmd.metadata = metadata;
        cmd.ipAddress = ip;
        cmd.deviceInfo = deviceInfo;
        cmd.source = "user";
        cmd.autoGenerated = false;

        return record(cmd);
    }

    public UserAction recordSystemAction(Long actorIdNullable,
                                         Long targetIdNullable,
                                         UserActionType type,
                                         UserActionCategory category,
                                         Long weddingId,
                                         Long matchId,
                                         Long actionGroupId,
                                         String metadata,
                                         String reason) {

        CreateActionCommand cmd = new CreateActionCommand();
        cmd.actorUserId = (actorIdNullable != null) ? actorIdNullable : requireSystemActorUserId();
        cmd.targetUserId = targetIdNullable;
        cmd.actionType = type;
        cmd.category = category;
        cmd.weddingId = weddingId;
        cmd.matchId = matchId;
        cmd.actionGroupId = actionGroupId;
        cmd.metadata = metadata;
        cmd.reason = reason;
        cmd.source = "system";
        cmd.autoGenerated = true;

        cmd.enforceRateLimit = false;
        cmd.enforceCooldownSameType = false;
        cmd.preventDuplicates = false;

        return record(cmd);
    }

    // =====================================================
    // ✅ Read APIs
    // =====================================================

    @Transactional(readOnly = true)
    public List<UserAction> getByActor(Long actorId, boolean activeOnly, int limit) {
        if (actorId == null) return Collections.emptyList();
        Pageable p = page(limit);
        return activeOnly
                ? repo.findByActor_IdAndActiveTrueOrderByCreatedAtDesc(actorId, p)
                : repo.findByActor_IdOrderByCreatedAtDesc(actorId, p);
    }

    @Transactional(readOnly = true)
    public List<UserAction> getByTarget(Long targetId, boolean activeOnly, int limit) {
        if (targetId == null) return Collections.emptyList();
        Pageable p = page(limit);
        return activeOnly
                ? repo.findByTarget_IdAndActiveTrueOrderByCreatedAtDesc(targetId, p)
                : repo.findByTarget_IdOrderByCreatedAtDesc(targetId, p);
    }

    @Transactional(readOnly = true)
    public List<UserAction> getByActorAndType(Long actorId, UserActionType type, boolean activeOnly, int limit) {
        if (actorId == null || type == null) return Collections.emptyList();
        Pageable p = page(limit);
        return activeOnly
                ? repo.findByActor_IdAndActionTypeAndActiveTrueOrderByCreatedAtDesc(actorId, type, p)
                : repo.findByActor_IdAndActionTypeOrderByCreatedAtDesc(actorId, type, p);
    }

    @Transactional(readOnly = true)
    public List<UserAction> getByActorAndCategory(Long actorId, UserActionCategory category, boolean activeOnly, int limit) {
        if (actorId == null || category == null) return Collections.emptyList();
        Pageable p = page(limit);
        return activeOnly
                ? repo.findByActor_IdAndCategoryAndActiveTrueOrderByCreatedAtDesc(actorId, category, p)
                : repo.findByActor_IdAndCategoryOrderByCreatedAtDesc(actorId, category, p);
    }

    @Transactional(readOnly = true)
    public List<UserAction> getByWedding(Long weddingId, int limit) {
        if (weddingId == null) return Collections.emptyList();
        return repo.findByWeddingIdOrderByCreatedAtDesc(weddingId, page(limit));
    }

    @Transactional(readOnly = true)
    public List<UserAction> getByOriginWedding(Long originWeddingId, int limit) {
        if (originWeddingId == null) return Collections.emptyList();
        return repo.findByOriginWeddingIdOrderByCreatedAtDesc(originWeddingId, page(limit));
    }

    @Transactional(readOnly = true)
    public List<UserAction> getByMatch(Long matchId, int limit) {
        if (matchId == null) return Collections.emptyList();
        return repo.findByMatchIdOrderByCreatedAtDesc(matchId, page(limit));
    }

    @Transactional(readOnly = true)
    public List<UserAction> getByGroup(Long actionGroupId, int limit) {
        if (actionGroupId == null) return Collections.emptyList();
        List<UserAction> rows = repo.findByActionGroupId(actionGroupId);
        rows = sortByCreatedDesc(rows);
        return limit(rows, limit);
    }

    @Transactional(readOnly = true)
    public List<UserAction> getRecentForActor(Long actorId, Duration window, int limit) {
        if (actorId == null || window == null) return Collections.emptyList();
        LocalDateTime since = LocalDateTime.now().minusSeconds(Math.max(1, window.getSeconds()));
        return repo.findByActor_IdAndCreatedAtAfter(actorId, since, page(limit));
    }

    @Transactional(readOnly = true)
    public List<UserAction> searchByMetadata(String text, int limit) {
        if (text == null || text.isBlank()) return Collections.emptyList();
        List<UserAction> rows = repo.findByMetadataContainingIgnoreCase(text.trim());
        return limit(rows, limit);
    }

    // =====================================================
    // ✅ Mutations / Purge
    // =====================================================

    public UserAction deactivate(Long actionId, String reason) {
        UserAction ua = repo.findById(actionId)
                .orElseThrow(() -> new IllegalArgumentException("UserAction not found: " + actionId));
        ua.setActive(false);
        if (reason != null && !reason.isBlank()) ua.setReason(reason.trim());
        ua.setUpdatedAt(LocalDateTime.now());
        return repo.save(ua);
    }

    public UserAction reactivate(Long actionId, String reason) {
        UserAction ua = repo.findById(actionId)
                .orElseThrow(() -> new IllegalArgumentException("UserAction not found: " + actionId));
        ua.setActive(true);
        if (reason != null && !reason.isBlank()) ua.setReason(reason.trim());
        ua.setUpdatedAt(LocalDateTime.now());
        return repo.save(ua);
    }

    public long purgeOld() {
        int daysActive = getIntSetting(K_PURGE_DAYS_ACTIVE, 365);
        int daysInactive = getIntSetting(K_PURGE_DAYS_INACTIVE, 90);

        LocalDateTime cutoffActive = LocalDateTime.now().minusDays(daysActive);
        LocalDateTime cutoffInactive = LocalDateTime.now().minusDays(daysInactive);

        long deleted = 0;
        deleted += repo.deleteByCreatedAtBeforeAndActiveFalse(cutoffInactive);
        deleted += repo.deleteByCreatedAtBefore(cutoffActive);
        return deleted;
    }

    // =====================================================
    // ✅ Stats
    // =====================================================

    @Transactional(readOnly = true)
    public long countByActor(Long actorId) {
        if (actorId == null) return 0;
        return repo.countByActor_Id(actorId);
    }

    @Transactional(readOnly = true)
    public long countByType(UserActionType type) {
        if (type == null) return 0;
        return repo.countByActionType(type);
    }

    @Transactional(readOnly = true)
    public long countByCategory(UserActionCategory category) {
        if (category == null) return 0;
        return repo.countByCategory(category);
    }

    @Transactional(readOnly = true)
    public long countByWedding(Long weddingId) {
        if (weddingId == null) return 0;
        return repo.countByWeddingId(weddingId);
    }

    @Transactional(readOnly = true)
    public long countByActorAndWedding(Long actorId, Long weddingId) {
        if (actorId == null || weddingId == null) return 0;
        return repo.countByActor_IdAndWeddingId(actorId, weddingId);
    }

    // =====================================================
    // 🔒 Rate Limit / Cooldown / Duplicate detection
    // =====================================================

    private void enforceRateLimitAnyAction(Long actorId, UserActionType type) {
        int minSeconds = getIntSetting(K_RATE_MIN_SECONDS, 2);
        int minSecondsHeavy = getIntSetting(K_RATE_MIN_SECONDS_HEAVY, 5);

        boolean heavy = isHeavy(type);
        LocalDateTime since = LocalDateTime.now().minusSeconds(heavy ? minSecondsHeavy : minSeconds);

        if (repo.existsByActor_IdAndCreatedAtAfter(actorId, since)) {
            throw new IllegalStateException("Rate limit: actorId=" + actorId);
        }
    }

    private void enforceCooldownSameType(Long actorId, UserActionType type) {
        if (type == null) return;
        int minSeconds = getIntSetting(K_RATE_MIN_SECONDS, 2);
        LocalDateTime since = LocalDateTime.now().minusSeconds(minSeconds);

        if (repo.existsByActor_IdAndActionTypeAndCreatedAtAfter(actorId, type, since)) {
            throw new IllegalStateException("Cooldown: actorId=" + actorId + " type=" + type);
        }
    }

    private UserAction findRecentDuplicate(CreateActionCommand cmd) {
        if (cmd.targetUserId == null) return null;

        int win = getIntSetting(K_RATE_WINDOW_DUP_SECONDS, 10);
        LocalDateTime since = LocalDateTime.now().minusSeconds(win);

        List<UserAction> rows = repo.findRecentDuplicateWithContext(
                cmd.actorUserId,
                cmd.targetUserId,
                cmd.actionType,
                cmd.category,
                since,
                cmd.weddingId,
                cmd.originWeddingId,
                cmd.matchId,
                PageRequest.of(0, 1)
        );

        return (rows == null || rows.isEmpty()) ? null : rows.get(0);
    }

    private boolean isHeavy(UserActionType type) {
        if (type == null) return false;

        String raw = settings.getEffectiveStringOrDefault(
                settings.resolveEnv(),
                SystemSettingsService.Scope.SYSTEM,
                null,
                K_HEAVY_ACTION_TYPES,
                null
        );

        if (raw == null || raw.isBlank()) return false;

        Set<String> heavySet = Arrays.stream(raw.split("[,;\\s]+"))
                .filter(s -> s != null && !s.isBlank())
                .map(String::trim)
                .map(String::toUpperCase)
                .collect(Collectors.toSet());

        return heavySet.contains(type.name().toUpperCase());
    }

    // =====================================================
    // 🧠 Anti-spam monitor (Signal בלבד)
    // =====================================================

    private void monitorSuspiciousIfEnabled(Long actorId) {
        boolean enabled = getBooleanSetting(K_MONITOR_ENABLED, true);
        if (!enabled) return;

        int windowSeconds = getIntSetting(K_MONITOR_WINDOW_SECONDS, 180);
        int threshold = getIntSetting(K_MONITOR_THRESHOLD, 30);

        LocalDateTime since = LocalDateTime.now().minusSeconds(Math.max(10, windowSeconds));
        List<UserAction> recent = repo.findByActor_IdAndCreatedAtAfter(actorId, since);

        if (recent != null && recent.size() >= threshold) {
            try {
                systemLogService.logTrace(
                        SystemActionType.SECURITY_SUSPICIOUS_MATCH_ACTIVITY,
                        SystemModule.USER_ACTION_SERVICE,
                        SystemSeverityLevel.WARNING,
                        true,
                        actorId,
                        null,
                        null,
                        null,
                        "UserAction monitor threshold hit: actorId=" + actorId + " count=" + recent.size() + " windowSeconds=" + windowSeconds,
                        null,
                        true
                );
            } catch (Exception ignore) {}
        }
    }

    private void auditIfNeeded(CreateActionCommand cmd, Long actorUserId, String details) {
        boolean enabled = getBooleanSetting(K_AUDIT_ENABLED, true);
        if (!enabled) return;
        if (cmd.auditActionType == null || cmd.auditModule == null) return;

        try {
            systemLogService.logTrace(
                    cmd.auditActionType,
                    cmd.auditModule,
                    (cmd.auditSeverity != null ? cmd.auditSeverity : SystemSeverityLevel.INFO),
                    true,
                    actorUserId,
                    safeTrim(cmd.auditRequestId),
                    safeTrim(cmd.ipAddress),
                    safeTrim(cmd.deviceInfo),
                    details,
                    safeTrim(cmd.auditContextJson),
                    cmd.auditAutomated
            );
        } catch (Exception ignore) {}
    }

    private void enforceUserState(CreateActionCommand cmd, User actor) {
        if (!(cmd.requireCanLike || cmd.requireCanSendMessage)) return;

        UserStateEvaluatorService.UserStateSummary st = userStateEvaluator.evaluateUserState(actor);
        List<String> reasons = (st != null && st.getReasonsBlocked() != null) ? st.getReasonsBlocked() : List.of();

        if (cmd.requireCanLike && (st == null || !st.isCanLike())) {
            throw new IllegalStateException("User cannot like: " + String.join(" | ", reasons));
        }
        if (cmd.requireCanSendMessage && (st == null || !st.isCanSendMessage())) {
            throw new IllegalStateException("User cannot send message: " + String.join(" | ", reasons));
        }
    }

    private void validateCmd(CreateActionCommand cmd) {
        if (cmd.actorUserId == null) throw new IllegalArgumentException("actorUserId is null");
        if (cmd.actionType == null) throw new IllegalArgumentException("actionType is null");
        if (cmd.category == null) throw new IllegalArgumentException("category is null");
    }

    private User getUserOrThrow(Long id) {
        return userRepo.findById(id)
                .orElseThrow(() -> new IllegalArgumentException("User not found: " + id));
    }

    private Long nextGroupIdIfMissing(CreateActionCommand cmd) {
        boolean need =
                cmd.matchId != null ||
                        (cmd.listName != null && !cmd.listName.isBlank()) ||
                        (cmd.metadata != null && cmd.metadata.length() > 30);

        if (!need) return null;

        long micros = System.currentTimeMillis() * 1_000L;
        int seq = Math.floorMod(groupSeq.incrementAndGet(), 1000);
        return (micros * 1_000L) + (nodeSalt % 1_000L) * 1000L + seq;
    }

    private Long requireSystemActorUserId() {
        String raw = settings.getEffectiveStringOrDefault(
                settings.resolveEnv(),
                SystemSettingsService.Scope.SYSTEM,
                null,
                K_SYSTEM_ACTOR_USER_ID,
                null
        );

        if (raw == null || raw.isBlank()) {
            throw new IllegalStateException("System actor is required. Set SystemSettings key: " + K_SYSTEM_ACTOR_USER_ID);
        }

        try {
            return Long.parseLong(raw.trim());
        } catch (NumberFormatException e) {
            throw new IllegalStateException("Invalid systemActorUserId in SystemSettings: " + raw);
        }
    }

    private int getIntSetting(String key, int def) {
        String raw = settings.getEffectiveStringOrDefault(
                settings.resolveEnv(),
                SystemSettingsService.Scope.SYSTEM,
                null,
                key,
                String.valueOf(def)
        );

        try {
            return Integer.parseInt(raw.trim());
        } catch (Exception ignore) {
            return def;
        }
    }

    private boolean getBooleanSetting(String key, boolean def) {
        String raw = settings.getEffectiveStringOrDefault(
                settings.resolveEnv(),
                SystemSettingsService.Scope.SYSTEM,
                null,
                key,
                String.valueOf(def)
        );
        return "true".equalsIgnoreCase(raw.trim()) || "1".equals(raw.trim());
    }

    private Pageable page(int limit) {
        int max = getIntSetting(K_MAX_PAGE_SIZE, 200);
        int size = (limit <= 0) ? Math.min(50, max) : Math.min(limit, max);
        return PageRequest.of(0, size);
    }

    private static String safeTrim(String s) {
        return (s == null) ? null : s.trim();
    }

    private static List<UserAction> limit(List<UserAction> rows, int limit) {
        if (rows == null || rows.isEmpty()) return Collections.emptyList();
        if (limit <= 0 || rows.size() <= limit) return rows;
        return rows.subList(0, limit);
    }

    private static List<UserAction> sortByCreatedDesc(List<UserAction> rows) {
        if (rows == null) return Collections.emptyList();
        return rows.stream()
                .filter(Objects::nonNull)
                .sorted(Comparator.comparing(UserAction::getCreatedAt, Comparator.nullsLast(Comparator.reverseOrder())))
                .collect(Collectors.toList());
    }
}