package com.example.myproject.service;

import com.example.myproject.model.*;
import com.example.myproject.repository.UserActionRepository;
import com.example.myproject.repository.UserRepository;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.List;
import java.util.stream.Collectors;

@Service
@Transactional
public class UserActionService {

    private final UserActionRepository userActionRepository;
    private final UserRepository userRepository;
    private final MatchService matchService;
    private final NotificationService notificationService;

    // =====================================================
    // 🔵 Constructor
    // =====================================================

    public UserActionService(UserActionRepository userActionRepository,
                             UserRepository userRepository,
                             MatchService matchService,
                             NotificationService notificationService) {
        this.userActionRepository = userActionRepository;
        this.userRepository = userRepository;
        this.matchService = matchService;
        this.notificationService = notificationService;
    }

    // =====================================================
    // 1️⃣ עזר: טעינת משתמשים
    // =====================================================

    private User loadUserOrThrow(Long userId, String messagePrefix) {
        if (userId == null) {
            throw new IllegalArgumentException(messagePrefix + " - userId is null");
        }
        return userRepository.findById(userId)
                .orElseThrow(() -> new IllegalArgumentException(messagePrefix + userId));
    }

    // =====================================================
    // 2️⃣ מתודת ליבה: יצירת UserAction אחת
    // =====================================================

    /**
     * מתודה פנימית שמייצרת UserAction ושומרת אותו.
     * משמשת את כל שאר הפעולות (LIKE/DISLIKE/FREEZE/VIEW וכו').
     */
    private UserAction recordActionInternal(Long actorId,
                                            Long targetUserId,
                                            Long weddingId,
                                            Long originWeddingId,
                                            Long matchId,
                                            UserActionType actionType,
                                            UserActionCategory categoryOverride,
                                            String metadata,
                                            String source,
                                            boolean autoGenerated,
                                            String listName,
                                            Long actionGroupId) {

        User actor = loadUserOrThrow(actorId, "Actor not found: ");

        User target = null;
        if (targetUserId != null) {
            target = loadUserOrThrow(targetUserId, "Target not found: ");
        }

        UserAction action = new UserAction();
        action.setActor(actor);
        action.setTarget(target);
        action.setActionType(actionType);

        // אם לא מגיע override – נבחר קטגוריה לפי טיפוס
        UserActionCategory category = (categoryOverride != null)
                ? categoryOverride
                : UserActionCategory.SOCIAL;

        action.setCategory(category);
        action.setWeddingId(weddingId);
        action.setOriginWeddingId(originWeddingId);
        action.setMatchId(matchId);
        action.setActionGroupId(actionGroupId);
        action.setSource(source != null ? source : "user");
        action.setAutoGenerated(autoGenerated);
        action.setMetadata(metadata);
        action.setListName(listName);
        action.setActive(true);
        action.setCreatedAt(LocalDateTime.now());
        action.setUpdatedAt(LocalDateTime.now());

        return userActionRepository.save(action);
    }

    /**
     * מתודה גנרית PUBLIC – לשימוש מצד קונטרולרים / שירותים אחרים.
     * זהה ל־recordActionInternal אבל חשופה החוצה.
     */
    public UserAction recordUserAction(Long actorId,
                                       Long targetUserId,
                                       Long weddingId,
                                       Long originWeddingId,
                                       Long matchId,
                                       UserActionType actionType,
                                       UserActionCategory category,
                                       String metadata,
                                       String source,
                                       boolean autoGenerated,
                                       String listName,
                                       Long actionGroupId) {

        return recordActionInternal(
                actorId,
                targetUserId,
                weddingId,
                originWeddingId,
                matchId,
                actionType,
                category,
                metadata,
                source,
                autoGenerated,
                listName,
                actionGroupId
        );
    }

    // =====================================================================
    // 3️⃣ שליפות בסיסיות מ־UserActionRepository
    // =====================================================================

    @Transactional(readOnly = true)
    public List<UserAction> getActionsByActor(Long actorId) {
        return userActionRepository.findByActorId(actorId);
    }

    @Transactional(readOnly = true)
    public List<UserAction> getActiveActionsByActor(Long actorId) {
        return userActionRepository.findByActorIdAndActiveTrue(actorId);
    }

    @Transactional(readOnly = true)
    public List<UserAction> getActionsByTarget(Long targetId) {
        return userActionRepository.findByTargetId(targetId);
    }

    @Transactional(readOnly = true)
    public List<UserAction> getActiveActionsByTarget(Long targetId) {
        return userActionRepository.findByTargetIdAndActiveTrue(targetId);
    }

    @Transactional(readOnly = true)
    public List<UserAction> getActionsByType(UserActionType type) {
        return userActionRepository.findByActionType(type);
    }

    @Transactional(readOnly = true)
    public List<UserAction> getActionsByWedding(Long weddingId) {
        return userActionRepository.findByWeddingId(weddingId);
    }

    @Transactional(readOnly = true)
    public List<UserAction> getActionsByMatch(Long matchId) {
        return userActionRepository.findByMatchId(matchId);
    }

    // =====================================================================
    // 4️⃣ פעולות משתמש: LIKE / DISLIKE / FREEZE / UNFREEZE / VIEW
    // =====================================================================

    /**
     * לייק למשתמש אחר.
     * - יוצר פעולה מסוג LIKE
     * - מעדכן listName = "LIKE"
     * - מכבה דיסלייק/קפוא קודמים
     */
    public UserAction likeUser(Long actorId, Long targetUserId, Long weddingId) {

        if (actorId == null || targetUserId == null)
            throw new IllegalArgumentException("actorId and targetUserId are required");

        if (actorId.equals(targetUserId))
            throw new IllegalArgumentException("Cannot like yourself.");

        // תיעוד הפעולה
        UserAction action = recordActionInternal(
                actorId,
                targetUserId,
                weddingId,
                weddingId,                    // originWeddingId
                null,                         // matchId
                UserActionType.LIKE,
                UserActionCategory.SOCIAL,
                null,
                "user",
                false,
                "LIKE",
                null
        );

        // כיבוי פעולות שליליות קודמות
        deactivatePreviousActions(actorId, targetUserId, UserActionType.DISLIKE);
        deactivatePreviousActions(actorId, targetUserId, UserActionType.FREEZE);

        return action;
    }

    /**
     * דיסלייק — מבטל לייק קיים + מסמן כ"לא מעוניין".
     * - listName = "DISLIKE"
     * - מכבה LIKE קודמים
     * - שולח התראה USER_DISLIKED לצד השני
     */
    public UserAction dislikeUser(Long actorId, Long targetUserId, Long weddingId) {

        UserAction action = recordActionInternal(
                actorId,
                targetUserId,
                weddingId,
                weddingId,
                null,
                UserActionType.DISLIKE,
                UserActionCategory.SOCIAL,
                null,
                "user",
                false,
                "DISLIKE",
                null
        );

        // כיבוי LIKE פעיל
        deactivatePreviousActions(actorId, targetUserId, UserActionType.LIKE);

        // שליחת התראה (לפי האפיון)
        notificationService.notifyUserDisliked(targetUserId, actorId);

        return action;
    }

    /**
     * הקפאת משתמש — כניסה לרשימת "מקפיא".
     * - listName = "FREEZE"
     * - מכבה כל FREEZE קודמים
     * - שולח התראה USER_FROZEN
     */
    public UserAction freezeUser(Long actorId, Long targetUserId, Long weddingId) {

        UserAction freeze = recordActionInternal(
                actorId,
                targetUserId,
                weddingId,
                weddingId,
                null,
                UserActionType.FREEZE,
                UserActionCategory.SOCIAL,
                null,
                "user",
                false,
                "FREEZE",
                null
        );

        // כיבוי FREEZE קודמים
        deactivatePreviousActions(actorId, targetUserId, UserActionType.FREEZE, freeze.getId());

        // התראה
        notificationService.notifyUserFreezeApplied(targetUserId, actorId);

        return freeze;
    }

    /**
     * ביטול קפיאה — UNFREEZE
     * - מסיר כל FREEZE פעילים
     * - listName = "UNFREEZE" (רק היסטוריה)
     * - שולח התראה USER_UNFROZEN
     */
    public UserAction unfreezeUser(Long actorId, Long targetUserId) {

        // כיבוי FREEZE פעיל
        deactivatePreviousActions(actorId, targetUserId, UserActionType.FREEZE);

        // תיעוד UNFREEZE
        UserAction action = recordActionInternal(
                actorId,
                targetUserId,
                null,
                null,
                null,
                UserActionType.UNFREEZE,
                UserActionCategory.SOCIAL,
                null,
                "user",
                false,
                "UNFREEZE",
                null
        );

        notificationService.notifyUserUnfreezeApplied(targetUserId, actorId);

        return action;
    }

    /**
     * צפייה בפרופיל — VIEW
     * - listName = "VIEW"
     * - משתמשים בסטטיסטיקה לצפיות בפרופיל (SUMMARY)
     */
    public UserAction viewProfile(Long actorId, Long targetUserId, Long weddingId) {

        return recordActionInternal(
                actorId,
                targetUserId,
                weddingId,
                weddingId,
                null,
                UserActionType.VIEW,
                UserActionCategory.SOCIAL,
                null,
                "user",
                false,
                "VIEW",
                null
        );
    }

    // =====================================================================
    // 5️⃣ עזר: כיבוי פעולות קודמות
    // =====================================================================

    /**
     * מכבה (active=false) פעולה קודמת מאותו סוג בין אותם משתמשים.
     */
    private void deactivatePreviousActions(Long actorId,
                                           Long targetId,
                                           UserActionType type) {

        User actor = loadUserOrThrow(actorId, "Actor not found: ");
        User target = loadUserOrThrow(targetId, "Target not found: ");

        userActionRepository.findByActorAndTarget(actor, target)
                .stream()
                .filter(a -> a.isActive() && a.getActionType() == type)
                .forEach(a -> {
                    a.setActive(false);
                    a.setUpdatedAt(LocalDateTime.now());
                    userActionRepository.save(a);
                });
    }

    /**
     * כיבוי קודמים פרט לפעולה שכרגע נוצרה.
     */
    private void deactivatePreviousActions(Long actorId,
                                           Long targetId,
                                           UserActionType type,
                                           Long excludeId) {

        User actor = loadUserOrThrow(actorId, "Actor not found: ");
        User target = loadUserOrThrow(targetId, "Target not found: ");

        userActionRepository.findByActorAndTarget(actor, target)
                .stream()
                .filter(a -> !a.getId().equals(excludeId))
                .filter(a -> a.isActive() && a.getActionType() == type)
                .forEach(a -> {
                    a.setActive(false);
                    a.setUpdatedAt(LocalDateTime.now());
                    userActionRepository.save(a);
                });
    }

    // =====================================================================
    // 6️⃣ רשימות לפי listName (LIKE / DISLIKE / FREEZE / VIEW)
    // =====================================================================

    /**
     * כל הפעולות הפעילות של משתמש ברשימה מסוימת (LIKE / DISLIKE / FREEZE / VIEW וכו').
     */
    @Transactional(readOnly = true)
    public List<UserAction> getListForUser(Long actorId, String listName) {
        return userActionRepository.findByActorIdAndListName(actorId, listName)
                .stream()
                .filter(UserAction::isActive)
                .collect(Collectors.toList());
    }

    @Transactional(readOnly = true)
    public List<UserAction> getMyLikes(Long actorId) {
        return getListForUser(actorId, "LIKE");
    }

    @Transactional(readOnly = true)
    public List<UserAction> getMyDislikes(Long actorId) {
        return getListForUser(actorId, "DISLIKE");
    }

    @Transactional(readOnly = true)
    public List<UserAction> getMyFreezes(Long actorId) {
        return getListForUser(actorId, "FREEZE");
    }

    @Transactional(readOnly = true)
    public List<UserAction> getMyProfileViews(Long actorId) {
        return getListForUser(actorId, "VIEW");
    }

    // =====================================================================
    // 7️⃣ סיכום צפיות בפרופיל (לפי אפיון 2025 + NotificationService)
    // =====================================================================

    /**
     * ספירת צפיות בפרופיל של משתמש בתקופה מסוימת.
     * משתמש ב־findByCreatedAtBetween ואז מסנן ב-Java.
     */
    @Transactional(readOnly = true)
    public int countProfileViewsForUserInPeriod(Long userId,
                                                LocalDateTime from,
                                                LocalDateTime to) {

        List<UserAction> allInPeriod =
                userActionRepository.findByCreatedAtBetween(from, to);

        return (int) allInPeriod.stream()
                .filter(a -> a.getTarget() != null
                        && a.getTarget().getId().equals(userId)
                        && a.getActionType() == UserActionType.VIEW)
                .count();
    }

    /**
     * יצירת התראת סיכום צפיות בפרופיל למשתמש (שימוש ב-NotificationService).
     */
    public void sendProfileViewsSummary(Long userId,
                                        String periodLabel,
                                        LocalDateTime from,
                                        LocalDateTime to) {

        int views = countProfileViewsForUserInPeriod(userId, from, to);
        notificationService.notifyProfileViewsSummary(userId, periodLabel, views);
    }
}